# 文件级分析：
# - 职责：Spring Boot主配置文件，定义应用程序的核心配置参数
# - 位置考虑：resources目录下，Spring Boot自动加载的标准位置
# - 命名原因：Spring Boot约定的主配置文件名
# - 调用关系：被Spring Boot启动时自动加载，为各个组件提供配置参数
#
# 设计思路：
# 1. 使用YAML格式，层次清晰，易于维护
# 2. 采用profile分离不同环境配置
# 3. 合理组织配置项，按功能模块分组
# 4. 设置合理的默认值，降低配置复杂度

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Spring框架配置
spring:
  # 环境配置 - 默认开发环境
  profiles:
    active: dev
  
  # 应用信息
  application:
    name: ecommerce-backend
    
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # 连接池配置 (HikariCP)
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: EcommerceHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update  # 开发环境自动更新表结构，生产环境应设为validate
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Shanghai
    open-in-view: false  # 关闭懒加载，避免N+1问题
    
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
          
  # Jackson配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE  # 下划线命名
    default-property-inclusion: NON_NULL  # 忽略null值
    
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      
  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1小时

# 日志配置
logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ecommerce.log
    max-size: 100MB
    max-history: 30

# Actuator监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# API文档配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: 电商系统API文档
    description: Spring Boot 3.x 电商系统后端接口文档
    version: 1.0.0
    contact:
      name: 开发团队
      email: dev@ecommerce.com

# 应用自定义配置
app:
  # JWT配置
  jwt:
    secret: ecommerce-secret-key-2024-very-long-and-secure-key-for-jwt-token-generation
    expiration: 86400000  # 24小时
    refresh-expiration: 604800000  # 7天
    header: Authorization
    prefix: "Bearer "
    
  # 文件存储配置
  file:
    upload-path: ./uploads/
    max-size: 10485760  # 10MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx
    
  # 业务配置
  business:
    default-page-size: 20
    max-page-size: 100
    order-timeout: 1800  # 订单超时时间30分钟（秒）